version: '2'
services:
  master:
    build: .
    image: ghost-mysql:master
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "33306:33306"
  slave:
    build:
      context: .
      dockerfile: Dockerfile-slave
    image: ghost-mysql:slave
    depends_on:
      - master
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_MASTER_SERVER=master
      - MYSQL_REPLICATION_USER=root
      - MYSQL_REPLICATION_PASS=root
      - MYSQL_MASTER_ROOT_PASS=root
      - MYSQL_MASTER_PORT=33306
      - MYSQL_MASTER_WAIT_TIME=10
    links:
      - master
    ports:
      - "33307:33307"
